### ISSUE TITLE
larger denominator options for ll

### ISSUE THREAD

**Issue by MichaelChirico** [r-gregmisc/gdata#1]
I'm trying to debug why I'm running out of memory from an R script and happened upon `ll`. I noticed that there's no option for `unit = 'GB'`, and further noticed that it should be simply to add this option by adding a `switch` case for the `denominator`.

I'm happy to make a PR if you'd like!

**Comment by warnes** [comment]
This is a good idea, a PR for this would wonderful!

**Comment by warnes** [comment]
@MichaelChirico I've just merged code that leverages `gdata::humanReadable` in `ll`, which allows sizes ranging from bytes to yottabyte, which should be enough, 😜  .
