### ISSUE TITLE
installXLSXsupport() is not working at all ?

### ISSUE THREAD

**Issue by tonyliang19** [r-gregmisc/gdata#10]
![image](https://user-images.githubusercontent.com/83138402/162094787-5b88fddf-e206-471b-9779-1b9747f01739.png)

**Comment by arni-magnusson** [comment]
Thanks for the feedback. The installXLSXsupport() function has been deprecated in gdata 2.19.0.

Please use other packages for Excel support, such as `openxlsx`, `readxl`, `XLConnect`, or `xlsx`.
