### ISSUE TITLE
Dropping Excel support

### ISSUE THREAD

**Issue by arni-magnusson** [r-gregmisc/gdata#11]
Hi Greg, I would be interested in streamlining the maintenance of the gdata package.

My proposal is to release `gdata` 3.0 without the read.xls() function.

Last year, I was creating a package (gfcmSTAR) for production use by the United Nations (FAO), importing fisheries data from Excel sheets and quality-controlling the data before database import. Normally, I would steer away from Excel for any data management, but for this project I needed a reliable pipeline from Excel into R. Therefore, I did a thorough comparison of packages that import Excel into R, to make an informed decision on what to depend on.

One important criterion is that the data are stored in modern Excel 'Table' objects (see [microsoft.com](https://support.microsoft.com/en-us/office/overview-of-excel-tables-7ab0bb7d-3a9e-4b56-a3c9-6c94334e492c) and [howtoexcel.org](https://www.howtoexcel.org/everything-you-need-to-know-about-excel-tables/)) that are well-defined XML entities that are a more reliable data container than cell ranges, especially when interfacing with other software and exporting.

As far as I could tell, read.xls() was not able to recognize named ranges, let alone named Table objects. This alone puts `gdata` well behind the `openxls`, `readxl`, `XLConnect`, and `xlsx` packages, and there are many other features that the other packages provide.

At this point, I think we would be doing `gdata` users a favor by pointing them to these packages, which are simply better at importing modern Excel files. The `gdata` package contains many excellent tools for data manipulation, and I think the package will improve by jettisoning the read.xls() function. Maintenance will become more streamlined, and any former users of read.xls() will have no problems using `openxlsx`, `readxl`, `XLConnect`, or `xlsx` for their Excel-to-R tasks.

**Comment by arni-magnusson** [comment]
One reason I'm raising this point is that after reading the https://github.com/r-gregmisc/gtools/issues/15 thread, I was wondering if I should volunteer to maintain the gdata package.

The read.xls() function was extremely valuable when it was first introduced, but at this point it seems more trouble than it's worth. Many users get confusing Perl messages when using gdata, even if they're not interested in the read.xlsx() function, and I would find it much easier to maintain gdata without it. Depending only on base R gives it the 'Chuck Norris' feel that many R users appreciate :)

**Comment by talgalili** [comment]
I'm fine dropping that function (it's a bit nostalgic for me, as I've used
it in the early days before the new packages arrived).
I suggest to replace the function with a deprecation message that would run
when invoking the function.

As for having you maintain the package, my vote is yes :)

**Comment by arni-magnusson** [comment]
![excel-shootout](https://user-images.githubusercontent.com/3720910/175800262-ce887451-5a0a-4951-96b6-1d60a627a524.png)

**Comment by arni-magnusson** [comment]
For most cases, I would recommend `openxlsx`, which requires only R and three packages: Rcpp, stringi, zip.

For gfcmSTAR, I opted for `XLConnect`, to import from Excel Table objects instead of ranges.

**Comment by talgalili** [comment]
LGTM

**Comment by bbolker** [comment]
I would say `readxl`'s dependency count is a little bit misleading because it's just "depends on tidyverse", but I don't have strong feelings about `readxl` vs `openxlsx`

**Comment by warnes** [comment]
I agree with dropping the xls/xlsx support.  In an ideal world, it would have gone through a deptication warning stage before removal some time ago, but at this point I think it should be dropped entirely only retaining stubs that generate a deprecated error message and directing users to the alternatives.

Sent with a Spark

**Comment by bbolker** [comment]
If @arni-magnusson is up for it I would still say that a short warning stage (6 months?) followed by hard deprecation would be better.

**Comment by warnes** [comment]
I’m OK with that, but I would suggest modifying the code to avoid package build failures when Perl is not available, since it appears that the Windows build servers no longer include Perl.

Sent with a Spark

**Comment by arni-magnusson** [comment]
That sounds reasonable. I'll take a look at the current build process, especially on Windows without Perl.

**Comment by arni-magnusson** [comment]
Hi, I would like to volunteer to maintain the gdata package at https://github.com/arni-magnusson/gdata. After a bit of jogging and massage, the package now:

1. Includes the 2.18.0.1 CRAN release (by Brian Ripley) in the commit history and a corresponding NEWS entry, tag, and release.
2. Combines development commits from all branches of https://github.com/r-gregmisc/gdata.
3. Documents all accumulated changes since 2.18.0 and 2.18.0.1 in the NEWS entry for an upcoming 2.19.0 release.
4. Rolls back ll() to a simple implementation that does not produce errors.
5. Simplifies things by removing renv.
6. Has an updated author and contributor list, based on \author{} entries.
7. Adds a 'deprecate' message to all Excel-related functions, which will be removed in a later 3.0.0 release.

The 2.19.0 CRAN release is ready to be submitted. Could @warnes and perhaps @bbolker and @talgalili take it for a quick test before I submit?

**Comment by bbolker** [comment]
I don't think I would be doing anything other than running `R CMD check` on it myself ... have you done reverse dependency checking yet?

**Comment by arni-magnusson** [comment]
Thanks Ben, that's a good call. Good citizenship to be proactive on that front and not just lay the burden on the CRAN maintenance team.

The R-Exts manual stops before reaching this important topic. Can you recommend certain tools and/or approaches to check reverse dependencies?

**Comment by bbolker** [comment]
The `revdepcheck` package https://github.com/r-lib/revdepcheck is fairly good.

**Comment by talgalili** [comment]
In general I'm fine with whatever you guys will decide to do.
From workong on gtools, I can say that the code coverage seemed rather minimal, so using R CMD check is a good minimal start for cran, but probably won't pick up on all possible issues that any change would cause. So just FYI.

**Comment by arni-magnusson** [comment]
On 15 April, I notified all package maintainers affected by deprecating read.xls() by email, covering both CRAN and Bioconductor. I'm getting "thanks for the heads up" responses, so it might be prudent to wait for a couple of weeks before a 2.19.0 CRAN release.

Greg, do you approve of me taking over the maintenance of the 'gdata' package?

**Comment by arni-magnusson** [comment]
On 15 April, I notified all package maintainers affected by deprecating read.xls() by email, covering both CRAN and Bioconductor. I'm getting "thanks for the heads up" responses, so it might be prudent to wait for a couple of weeks before a 2.19.0 CRAN release.

Greg @warnes, do you approve of me taking over the maintenance of the 'gdata' package?

**Comment by warnes** [comment]
Hi Arni (et al)

I’m fine with you taking over maintenance.  I have a (slight) preference that you use the gregmisc GitHub repo, but not enough to force it.

I fully support removing the read.xls()  code from the package.  (It had been my intent for some time to split the read.xls() code out into a separate package for the small number of people who still rely on it, but I never got around to it.).

-Greg


Gregory R. Warnes, Ph.D.
***@***.***
Eternity is a long time, take a friend!

**Comment by arni-magnusson** [comment]
Yes, let's look into that option. Can you elevate my https://github.com/r-gregmisc/gdata access to `admin`?

**Comment by warnes** [comment]
Done.

-G

Gregory R. Warnes, Ph.D.
***@***.***
Eternity is a long time, take a friend!

**Comment by arni-magnusson** [comment]
Excellent, thanks. I will maintain the package at https://github.com/r-gregmisc/gdata.

I've just submitted 2.19.0 to CRAN.

**Comment by bbolker** [comment]
This can be closed now, right?

**Comment by arni-magnusson** [comment]
Almost :) We've only added a deprecation message so far. Dropping Excel support should happen within the next few weeks, when we remove the Perl modules and release gdata 3.0.0.

**Comment by arni-magnusson** [comment]
> My proposal is to release gdata 3.0 without the read.xls() function.

[Done](https://github.com/r-gregmisc/gdata/releases/tag/3.0.0).
