### ISSUE TITLE
Note re: CVE on old gdata versions

### ISSUE THREAD

**Issue by MichaelChirico** [r-gregmisc/gdata#14]
Hi, thanks for maintaining {gdata}!

FYI I just filed this note about old {gdata} versions apparently affected by a CVE:

https://github.com/RConsortium/r-advisory-database/issues/11

Since that functionality is now removed, not sure there's anything to do, but it's definitely a strong reason to upgrade to the new CRAN release!

**Comment by arni-magnusson** [comment]
Hi, thanks for the heads up!

I see that https://github.com/RConsortium/r-advisory-database/issues/11 has been resolved on the r-advisory-database side.

This issue shows well that it was a good package design decision to remove the archaic and limited Excel support from the `gdata` package. I agree, definitely a strong reason to upgrade to the new CRAN release.
