### ISSUE TITLE
Convert from separate .Rd files to Roxygen inline documentation

### ISSUE THREAD

**Issue by warnes** [r-gregmisc/gdata#4]
Most (all?) of the work can be accomplished using
```
Rd2roxygen::Rd2roxygen("path/to/source/pkg")
```
see yihui.org/rd2roxygen

**Comment by arni-magnusson** [comment]
I'm liking the retro feel of editing Rd files :)

The official R-exts manual doesn't even mention that Roxygen exists, so we're going to pretend it doesn't exist for now :)
